# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish to Github Pages

on:
  push:
    branches: [ "main" ]
    paths:
    - "docs/**"
    - "public/**"
    - ".github/workflows/publish-docs.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:            # Job-level permissions configuration starts here
      contents: write       # 'write' access to repository contents
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/setup-node@v4
      with:
        node-version: latest
        check-latest: true
    - name: Set git name and email
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    - name: Install Yarn
      run: npm install -g yarn
    - name: Restore dependencies
      run: |
        dotnet tool restore
        dotnet paket restore
        dotnet restore
        yarn install
    - name: Build dotnet projects
      run: dotnet build --no-restore
    - name: Publish documentation to gh-pages
      run: yarn publish-docs
