name: Release version to Nuget

on:
  release:
    types:
    - published

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install Yarn
      run: npm install -g yarn
    - name: Restore dependencies
      run: |
        dotnet tool restore
        dotnet paket restore
        dotnet restore
        yarn install
    - name: Build dotnet projects
      run: dotnet build --no-restore
    - name: Pack dotnet projects
      run: yarn dotnet-pack
    - name: Publish to NuGet
      run: dotnet push --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} *.nupkg